version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker

  server_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server

  client_test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
  docker_image_build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            sudo docker build ./db -t radek467/cicd:database_image
            sudo docker push radek467/cicd:database_image
      - run:
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            sudo docker build ./server -t radek467/cicd:server_image
            sudo docker push radek467/cicd:server_image
      - run:
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            sudo docker build ./client -t radek467/cicd:client_image
            sudo docker push radek467/cicd:client_image
workflows:
  build-and-test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - server_test:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - client_test:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - docker_image_build:
          requires:
            - server_test
            - client_test
