version: 3.0
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
  server_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server
  client_test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
workflows:
  build-and-test:
    jobs:
      - build
      - server_test:
          requires:
            - build
      - client_test:
          requires:
            - build
